# - name: COMPOSER | Composer update
#   composer:
#     command: update
#     working_dir: "{{ ansistrano_release_path.stdout }}"
#     optimize_autoloader: yes
- name: COMPOSER | Composer install
  composer:
    command: install 
    no_dev: no
    working_dir: "{{ ansistrano_release_path.stdout }}"
    optimize_autoloader: yes
- name: COMPOSER | .env
  template:
    src: ../templates/env.j2
    dest: "{{ ansistrano_shared_path }}/.env"
