- name: LARAVEL | Composer update
  composer:
    command: update
    working_dir: "{{ ansistrano_release_path.stdout }}"
    optimize_autoloader: true
- name: LARAVEL | Composer install
  composer:
    command: install
    working_dir: "{{ ansistrano_release_path.stdout }}"
    optimize_autoloader: true
- name: LARAVEL | .env
  template:
    src: ../templates/env.j2
    dest: "{{ ansistrano_shared_path }}/.env"
